# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e611fb4e7f0a8480ff4f2abf2c6c251f12d93f3a8ef8383842c0cfe8f7dc4369b4e9c644e1b7fd40405a41e55bc52f318af2f0d9dd2ab09b05fa1274ad05f0c

test:
  secret_key_base: 4ca91c7b4ae986e9aa1022b596889284a09b9ffe3074232db5370d39792c30f81913016f35d722a7573716192428f8cb8aa2ad6cfe990fb0dd9b50c6e6a1e473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
